# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bryan West
email: sbw78@cornell.edu
description: ""
# description: >- # this means to ignore newlines until the next item
#   Social Psychology PhD candidate at Cornell University
domain: sbw78.github.io
url: "https://sbw78.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
show_excerpts: true
# excerpt_separator: "<!--more-->"

# Social Media
# twitter_username: sbwest
mastodon:
  - username: sbwest
    instance: mastodon.social
github_username:  sbw78
linkedin_username: bryan-west
# orcid: 0000-0003-3327-0499

# Build settings
theme: minima
#remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-target-blank
#  - jekyll-remote-theme

# header_pages:
#   - index.md
#   - blog.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
